services:
    # cURL client for Buzz
    buzz.client.file_get_contents:
        class:  Buzz\Client\FileGetContents
        public: false
        calls:
          - [setVerifyPeer, [false]]
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
          - [setVerifyPeer, [false]]

    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']

    site_status_service:
        class: Deeson\WardenBundle\Services\WardenRequestService
        arguments: ['@buzz.browser']

    drupal_update_service:
        class: Deeson\WardenBundle\Services\DrupalUpdateRequestService
        arguments: ['@buzz.browser']

    site_manager:
        class: Deeson\WardenBundle\Managers\SiteManager
        arguments: [@doctrine_mongodb]

    module_manager:
        class: Deeson\WardenBundle\Managers\ModuleManager
        arguments: [@doctrine_mongodb]

    site_have_issue_manager:
        class: Deeson\WardenBundle\Managers\SiteHaveIssueManager
        arguments: [@doctrine_mongodb]

    user_provider:
        class: Deeson\WardenBundle\Services\UserProviderService
        arguments: [%kernel.root_dir%]

    warden_setup:
        class: Deeson\WardenBundle\Services\WardenSetupService
        arguments: [%kernel.root_dir%]