imports:
    - { resource: config.yml }

framework:
    trusted_proxies:  [127.0.0.1]

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

# app/config/config.yml
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: warden
    document_managers:
        default:
            auto_mapping: true