
modules_list:
    path:    /modules
    defaults: { _controller: DeesonWardenDrupalBundle:Modules:index }

modules_show:
    path:    /modules/{projectName}
    defaults: { _controller: DeesonWardenDrupalBundle:Modules:show }
