_dashboard:
    pattern:  /
    defaults: { _controller: DeesonSiteStatusBundle:Default:index }

sites_list:
    path:    /sites
    defaults: { _controller: DeesonSiteStatusBundle:Sites:index }

sites_add:
    path:    /sites/add
    defaults: { _controller: DeesonSiteStatusBundle:Sites:add }

sites_show:
    path:    /sites/{id}
    defaults: { _controller: DeesonSiteStatusBundle:Sites:show }

sites_delete:
    path:    /sites/{id}/delete
    defaults: { _controller: DeesonSiteStatusBundle:Sites:delete }

sites_update_core:
    path:    /sites/{id}/update-core
    defaults: { _controller: DeesonSiteStatusBundle:Sites:updatecore }

modules_list:
    path:    /modules
    defaults: { _controller: DeesonSiteStatusBundle:Modules:index }

modules_show:
    path:    /modules/{id}
    defaults: { _controller: DeesonSiteStatusBundle:Modules:show }