parameters:
    site_config_file: %kernel.root_dir%/../src/Deeson/SiteStatusBundle/Resources/config/site_config.yml

services:
    # cURL client for Buzz
    buzz.client.file_get_contents:
        class:  Buzz\Client\FileGetContents
        public: false
        calls:
          - [setVerifyPeer, [false]]
    buzz.client.curl:
        class:  Buzz\Client\Curl
        public: false
        calls:
          - [setVerifyPeer, [false]]

    # Buzz browser
    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']

    site_status_service:
        class: Deeson\SiteStatusBundle\Services\SiteStatusRequestService
        arguments: ['@buzz.browser']

    drupal_update_service:
        class: Deeson\SiteStatusBundle\Services\DrupalUpdateRequestService
        arguments: ['@buzz.browser']

    site_manager:
        class: Deeson\SiteStatusBundle\Managers\SiteManager
        arguments: [@doctrine_mongodb]

    module_manager:
        class: Deeson\SiteStatusBundle\Managers\ModuleManager
        arguments: [@doctrine_mongodb]

    site_have_issue_manager:
        class: Deeson\SiteStatusBundle\Managers\SiteHaveIssueManager
        arguments: [@doctrine_mongodb]

    user_provider:
        class: Deeson\SiteStatusBundle\Services\UserProviderService
        arguments: [%site_config_file%]